import "./globals.css";
import Header from "./component/Header";
import Footer from "./component/Footer";

export const metadata = {
  title: "Video gallery",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="container">
          <div className="inner-container">
            <Header />
            {children}
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
